# https://pymarkdown.readthedocs.io/en/latest/rules/
plugins:
  # Use # style headings
  heading-style:
    enabled: true
    style: atx

  # Allow for long lines
  line-length:
    enabled: false

  # No need for a first line H1
  first-line-h1:
    enabled: false

extensions:
  front-matter:
    enabled: true
